# Bucketing Configuration

# Number of buckets per street
k_preflop: 12
k_flop: 60
k_turn: 40
k_river: 24

# Number of hands to sample for clustering
num_samples: 500000

# Random seed for reproducibility
seed: 42

# Feature extraction settings
features:
  use_equity: true
  use_position: true
  use_spr: true
  use_draws: true
  
# K-means settings
kmeans:
  n_init: 10
  max_iter: 300
  tol: 0.0001
