#!/usr/bin/env python3
"""
Demonstration of multi-instance parallel training.

This script shows how to use the --num-instances option to launch
multiple independent solver instances in parallel.
"""

import argparse
import sys
from pathlib import Path


def main():
    print("=" * 70)
    print("Multi-Instance Parallel Training - Demo and Examples")
    print("=" * 70)
    print()
    
    print("The multi-instance option allows you to launch multiple independent")
    print("solver instances in parallel, each with a single worker.")
    print()
    
    print("Key Features:")
    print("  ✓ Automatic work distribution across instances")
    print("  ✓ Separate output directories per instance")
    print("  ✓ Real-time progress monitoring")
    print("  ✓ Independent TensorBoard logs per instance")
    print("  ✓ Graceful shutdown on Ctrl+C")
    print()
    
    print("-" * 70)
    print("Example 1: Basic Usage (4 instances)")
    print("-" * 70)
    print()
    print("python -m holdem.cli.train_blueprint \\")
    print("  --buckets assets/abstraction/precomputed_buckets.pkl \\")
    print("  --logdir runs/multi_instance_demo \\")
    print("  --iters 100000 \\")
    print("  --num-instances 4")
    print()
    print("This will:")
    print("  - Launch 4 independent solver instances")
    print("  - Each processes 25,000 iterations")
    print("  - Results saved in runs/multi_instance_demo/instance_N/")
    print()
    
    print("-" * 70)
    print("Example 2: With Checkpointing")
    print("-" * 70)
    print()
    print("python -m holdem.cli.train_blueprint \\")
    print("  --buckets assets/abstraction/precomputed_buckets.pkl \\")
    print("  --logdir runs/multi_checkpoint \\")
    print("  --iters 1000000 \\")
    print("  --num-instances 8 \\")
    print("  --checkpoint-interval 10000")
    print()
    print("This will:")
    print("  - Launch 8 instances (125,000 iterations each)")
    print("  - Save checkpoints every 10,000 iterations")
    print("  - Each instance has its own checkpoints")
    print()
    
    print("-" * 70)
    print("Example 3: Large Scale Training")
    print("-" * 70)
    print()
    print("python -m holdem.cli.train_blueprint \\")
    print("  --buckets assets/abstraction/precomputed_buckets.pkl \\")
    print("  --logdir runs/large_scale \\")
    print("  --iters 10000000 \\")
    print("  --num-instances 16 \\")
    print("  --checkpoint-interval 50000 \\")
    print("  --epsilon 0.6")
    print()
    print("This will:")
    print("  - Launch 16 instances (625,000 iterations each)")
    print("  - Total of 10 million iterations")
    print("  - Exploration epsilon of 0.6")
    print()
    
    print("-" * 70)
    print("Progress Monitoring")
    print("-" * 70)
    print()
    print("During execution, you'll see real-time progress updates:")
    print()
    print("  ============================================================")
    print("  Overall Progress: 45.3%")
    print("  ------------------------------------------------------------")
    print("  Instance 0: ▶️ 47.2% (iter 11800/25000)")
    print("  Instance 1: ▶️ 45.8% (iter 11450/25000)")
    print("  Instance 2: ▶️ 43.9% (iter 10975/25000)")
    print("  Instance 3: ▶️ 44.5% (iter 11125/25000)")
    print("  ============================================================")
    print()
    
    print("-" * 70)
    print("Output Structure")
    print("-" * 70)
    print()
    print("runs/logdir/")
    print("├── progress/")
    print("│   ├── instance_0_progress.json")
    print("│   ├── instance_1_progress.json")
    print("│   └── ...")
    print("├── instance_0/")
    print("│   ├── instance_0.log")
    print("│   ├── checkpoint_10000.pkl")
    print("│   └── tensorboard/")
    print("├── instance_1/")
    print("│   └── ...")
    print("└── ...")
    print()
    
    print("-" * 70)
    print("Viewing Results")
    print("-" * 70)
    print()
    print("# View TensorBoard for a specific instance")
    print("tensorboard --logdir runs/logdir/instance_0/tensorboard")
    print()
    print("# View all instances together")
    print("tensorboard --logdir runs/logdir/")
    print()
    print("# Evaluate a specific instance's checkpoint")
    print("python -m holdem.cli.eval_blueprint \\")
    print("  --checkpoint runs/logdir/instance_0/checkpoint_final.pkl \\")
    print("  --buckets assets/abstraction/precomputed_buckets.pkl")
    print()
    
    print("-" * 70)
    print("Important Notes")
    print("-" * 70)
    print()
    print("✓ Compatible: --iters, --checkpoint-interval, --epsilon, --config")
    print("✗ Not compatible: --time-budget, --num-workers, --resume-from")
    print()
    print("Each instance runs independently with 1 worker.")
    print("Iterations are automatically distributed to avoid overlap.")
    print()
    
    print("=" * 70)
    print("For detailed documentation, see GUIDE_MULTI_INSTANCE.md")
    print("=" * 70)


if __name__ == "__main__":
    main()
